import type { Agent, FleetSummary } from "./types";

const now = new Date().toISOString();
const ago = (min: number) => new Date(Date.now() - min * 60000).toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();

export const agents: Agent[] = [
  {
    id: "sloane-01",
    name: "Sloane Navarro",
    owner: "Chris Steele",
    environment: "prod",
    tags: ["cto", "smart-contracts", "infrastructure"],
    slaTier: "critical",
    status: "online",
    lastHeartbeat: ago(2),
    lastSeen: ago(1),
    currentTask: "USDY oracle poster monitoring",
    queueDepth: 0,
    uptime: "14d 6h 23m",
    agentVersion: "2026.3.31",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw 2026.3.31",
    toolingVersion: "Node 22.22.2",
    versionDrift: true,
    host: { name: "Gideon-flicker-1", ip: "204.168.193.91", location: "Frankfurt, DE", cpu: 23, ram: 61, disk: 34, network: "healthy" },
    errors1h: 0,
    errors24h: 2,
    taskStartDelay: 340,
    completionTime: 12400,
    apiLatency: 180,
    cost: { today: 14.82, week: 89.50, month: 342.10, tokensToday: 1_240_000, model: "claude-opus-4-6" },
    permissions: ["exec", "read", "write", "web_fetch", "git", "deploy", "secrets"],
    lastBackup: daysAgo(1),
    lastRestoreTest: daysAgo(14),
    backupHealthy: true,
    secrets: { total: 8, expiringSoon: 1, expired: 0, lastRotation: daysAgo(7) },
    autoRestart: true,
    lastRestartReason: "Context compaction (85%)",
    lastRestartTime: ago(120),
    security: {
      patchLevel: "2026-04-18",
      lastOsUpdate: "2026-04-18",
      firewallStatus: "active",
      portsExposed: [443, 22],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: true,
      diskEncryption: true,
      mfaEnabled: false,
      auditLogEnabled: true,
      auditRetentionDays: 90,
      lastVulnScan: daysAgo(3),
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Tue/Thu 03:00-05:00 UTC",
    approvedModels: ["claude-opus-4-6", "claude-sonnet-4-20250514"],
    fallbackChain: ["claude-sonnet-4-20250514", "claude-haiku"],
    timeline: [
      { time: ago(120), type: "restart", message: "Auto-restart: context at 85%" },
      { time: ago(300), type: "deploy", message: "Pushed BetChamps.io landing + Privy integration" },
      { time: daysAgo(1), type: "deploy", message: "Oracle poster service deployed" },
      { time: daysAgo(2), type: "config", message: "Model override: claude-opus-4-6" },
      { time: daysAgo(4), type: "security", message: "Secrets rotation: GitHub PAT" },
      { time: daysAgo(6), type: "deploy", message: "USDY V1 contracts pushed to GitHub" },
    ],
  },
  {
    id: "henry-02",
    name: "Henry (Frontend)",
    owner: "Chris Steele",
    environment: "prod",
    tags: ["frontend", "react", "ui"],
    slaTier: "high",
    status: "online",
    lastHeartbeat: ago(5),
    lastSeen: ago(3),
    currentTask: "USDY vault confirmation UX",
    queueDepth: 2,
    uptime: "3d 14h 8m",
    agentVersion: "2026.4.15",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw 2026.4.15",
    toolingVersion: "Node 22.22.2",
    versionDrift: false,
    host: { name: "Henry-frontend-1", ip: "204.168.193.91", location: "Frankfurt, DE", cpu: 18, ram: 42, disk: 28, network: "healthy" },
    errors1h: 0,
    errors24h: 1,
    taskStartDelay: 210,
    completionTime: 8200,
    apiLatency: 150,
    cost: { today: 8.40, week: 52.30, month: 198.70, tokensToday: 720_000, model: "claude-sonnet-4-20250514" },
    permissions: ["exec", "read", "write", "web_fetch", "git"],
    lastBackup: daysAgo(1),
    lastRestoreTest: daysAgo(7),
    backupHealthy: true,
    secrets: { total: 4, expiringSoon: 0, expired: 0, lastRotation: daysAgo(14) },
    autoRestart: true,
    lastRestartReason: "Scheduled maintenance",
    lastRestartTime: daysAgo(3),
    security: {
      patchLevel: "2026-04-20",
      lastOsUpdate: "2026-04-20",
      firewallStatus: "active",
      portsExposed: [443],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: true,
      diskEncryption: true,
      mfaEnabled: false,
      auditLogEnabled: true,
      auditRetentionDays: 30,
      lastVulnScan: daysAgo(5),
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Mon/Wed 04:00-06:00 UTC",
    approvedModels: ["claude-sonnet-4-20250514"],
    fallbackChain: ["claude-haiku"],
    timeline: [
      { time: ago(180), type: "deploy", message: "Vault confirmation polling + TX display" },
      { time: daysAgo(1), type: "deploy", message: "VaultClient.tsx increaseAllowance fix" },
      { time: daysAgo(2), type: "config", message: "Added Vercel deploy hook" },
      { time: daysAgo(3), type: "restart", message: "Scheduled maintenance restart" },
    ],
  },
  {
    id: "oracle-03",
    name: "Oracle Poster",
    owner: "Sloane Navarro",
    environment: "prod",
    tags: ["oracle", "cron", "infrastructure"],
    slaTier: "critical",
    status: "degraded",
    lastHeartbeat: ago(45),
    lastSeen: ago(45),
    currentTask: "Price submission (stale — last post 45m ago)",
    queueDepth: 0,
    uptime: "0d 0h 0m",
    agentVersion: "1.0.0",
    latestVersion: "1.0.0",
    systemVersion: "Node 22.22.2",
    toolingVersion: "tsx",
    versionDrift: false,
    host: { name: "Gideon-flicker-1", ip: "204.168.193.91", location: "Frankfurt, DE", cpu: 2, ram: 8, disk: 34, network: "healthy" },
    errors1h: 3,
    errors24h: 3,
    taskStartDelay: 0,
    completionTime: 4500,
    apiLatency: 220,
    cost: { today: 0, week: 0, month: 0, tokensToday: 0, model: "N/A (script)" },
    permissions: ["blockchain-write", "price-feed-read"],
    lastBackup: null,
    lastRestoreTest: null,
    backupHealthy: false,
    secrets: { total: 1, expiringSoon: 0, expired: 0, lastRotation: null },
    autoRestart: false,
    lastRestartReason: "SIGTERM — exec session timeout",
    lastRestartTime: daysAgo(8),
    security: {
      patchLevel: "2026-04-18",
      lastOsUpdate: "2026-04-18",
      firewallStatus: "active",
      portsExposed: [],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: true,
      diskEncryption: true,
      mfaEnabled: false,
      auditLogEnabled: false,
      auditRetentionDays: 0,
      lastVulnScan: null,
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "N/A",
    approvedModels: [],
    fallbackChain: [],
    timeline: [
      { time: ago(45), type: "alert", message: "Oracle stale — last price 45 min ago" },
      { time: daysAgo(8), type: "crash", message: "SIGTERM: exec session expired" },
      { time: daysAgo(8), type: "deploy", message: "Initial oracle poster deployed" },
    ],
  },
  {
    id: "growth-04",
    name: "Growth Agent",
    owner: "Chris Steele",
    environment: "prod",
    tags: ["social", "content", "marketing"],
    slaTier: "medium",
    status: "online",
    lastHeartbeat: ago(8),
    lastSeen: ago(6),
    currentTask: "Drafting Twitter thread: USDY V1 launch",
    queueDepth: 1,
    uptime: "7d 2h 11m",
    agentVersion: "2026.4.15",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw 2026.4.15",
    toolingVersion: "Node 22.22.2",
    versionDrift: false,
    host: { name: "Growth-agent-1", ip: "45.77.142.18", location: "Amsterdam, NL", cpu: 12, ram: 35, disk: 22, network: "healthy" },
    errors1h: 0,
    errors24h: 0,
    taskStartDelay: 180,
    completionTime: 5400,
    apiLatency: 140,
    cost: { today: 4.20, week: 28.90, month: 112.40, tokensToday: 380_000, model: "claude-sonnet-4-20250514" },
    permissions: ["read", "web_fetch", "social-post"],
    lastBackup: daysAgo(1),
    lastRestoreTest: daysAgo(21),
    backupHealthy: true,
    secrets: { total: 3, expiringSoon: 0, expired: 0, lastRotation: daysAgo(30) },
    autoRestart: true,
    lastRestartReason: "Weekly scheduled restart",
    lastRestartTime: daysAgo(2),
    security: {
      patchLevel: "2026-04-15",
      lastOsUpdate: "2026-04-15",
      firewallStatus: "active",
      portsExposed: [443],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: true,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: true,
      auditRetentionDays: 30,
      lastVulnScan: daysAgo(10),
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Sun 02:00-04:00 UTC",
    approvedModels: ["claude-sonnet-4-20250514", "claude-haiku"],
    fallbackChain: ["claude-haiku"],
    timeline: [
      { time: ago(120), type: "deploy", message: "Content calendar updated" },
      { time: daysAgo(2), type: "restart", message: "Weekly scheduled restart" },
      { time: daysAgo(5), type: "config", message: "Added Twitter API credentials" },
    ],
  },
  {
    id: "monitor-05",
    name: "Infra Monitor",
    owner: "Sloane Navarro",
    environment: "prod",
    tags: ["monitoring", "alerts", "infrastructure"],
    slaTier: "high",
    status: "offline",
    lastHeartbeat: daysAgo(2),
    lastSeen: daysAgo(2),
    currentTask: null,
    queueDepth: 0,
    uptime: "0d 0h 0m",
    agentVersion: "2026.3.28",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw 2026.3.28",
    toolingVersion: "Node 22.22.2",
    versionDrift: true,
    host: { name: "Monitor-1", ip: "157.180.91.37", location: "New York, US", cpu: 0, ram: 0, disk: 67, network: "down" },
    errors1h: 0,
    errors24h: 0,
    taskStartDelay: 0,
    completionTime: 0,
    apiLatency: 0,
    cost: { today: 0, week: 0, month: 18.40, tokensToday: 0, model: "claude-haiku" },
    permissions: ["read", "web_fetch", "alerts"],
    lastBackup: daysAgo(3),
    lastRestoreTest: null,
    backupHealthy: false,
    secrets: { total: 2, expiringSoon: 2, expired: 0, lastRotation: daysAgo(60) },
    autoRestart: true,
    lastRestartReason: "Crash: unhandled API timeout",
    lastRestartTime: daysAgo(2),
    security: {
      patchLevel: "2026-03-28",
      lastOsUpdate: "2026-03-28",
      firewallStatus: "unknown",
      portsExposed: [443, 22, 9090],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: false,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: false,
      auditRetentionDays: 0,
      lastVulnScan: null,
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "N/A",
    approvedModels: ["claude-haiku"],
    fallbackChain: [],
    timeline: [
      { time: daysAgo(2), type: "crash", message: "Unhandled API timeout — process exited" },
      { time: daysAgo(2), type: "alert", message: "Agent offline — no heartbeat in 30m" },
      { time: daysAgo(5), type: "config", message: "Added Slack webhook for alerts" },
    ],
  },
  {
    id: "betchamps-06",
    name: "BetChamps Builder",
    owner: "Chris Steele",
    environment: "dev",
    tags: ["frontend", "betchamps", "base"],
    slaTier: "low",
    status: "online",
    lastHeartbeat: ago(15),
    lastSeen: ago(10),
    currentTask: "Idle — awaiting next task",
    queueDepth: 0,
    uptime: "0d 8h 42m",
    agentVersion: "2026.4.15",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw 2026.4.15",
    toolingVersion: "Node 22.22.2",
    versionDrift: false,
    host: { name: "BetChamps-dev-1", ip: "204.168.193.91", location: "Frankfurt, DE", cpu: 5, ram: 22, disk: 18, network: "healthy" },
    errors1h: 0,
    errors24h: 0,
    taskStartDelay: 150,
    completionTime: 6800,
    apiLatency: 160,
    cost: { today: 2.10, week: 2.10, month: 2.10, tokensToday: 180_000, model: "claude-sonnet-4-20250514" },
    permissions: ["exec", "read", "write", "git"],
    lastBackup: null,
    lastRestoreTest: null,
    backupHealthy: false,
    secrets: { total: 1, expiringSoon: 0, expired: 0, lastRotation: null },
    autoRestart: false,
    lastRestartReason: null,
    lastRestartTime: null,
    security: {
      patchLevel: "2026-04-21",
      lastOsUpdate: "2026-04-21",
      firewallStatus: "active",
      portsExposed: [443],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: true,
      diskEncryption: true,
      mfaEnabled: false,
      auditLogEnabled: true,
      auditRetentionDays: 7,
      lastVulnScan: ago(60),
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "N/A",
    approvedModels: ["claude-sonnet-4-20250514"],
    fallbackChain: ["claude-haiku"],
    timeline: [
      { time: ago(60), type: "deploy", message: "Privy wallet integration pushed" },
      { time: ago(180), type: "deploy", message: "Live markets UI + tournament spec" },
      { time: ago(300), type: "deploy", message: "Initial BetChamps.io landing page" },
    ],
  },
];

export function getFleetSummary(): FleetSummary {
  const total = agents.length;
  const online = agents.filter((a) => a.status === "online").length;
  const degraded = agents.filter((a) => a.status === "degraded").length;
  const offline = agents.filter((a) => a.status === "offline").length;
  const stuck = agents.filter((a) => a.status === "stuck").length;
  return { total, online, degraded, offline, stuck, healthyPct: Math.round((online / total) * 100) };
}

export function getNeedsAttention(): Agent[] {
  return agents.filter(
    (a) =>
      a.status === "offline" ||
      a.status === "stuck" ||
      a.status === "degraded" ||
      a.errors24h > 5 ||
      a.versionDrift ||
      a.secrets.expiringSoon > 0 ||
      a.secrets.expired > 0 ||
      a.security.criticalFindings > 0
  );
}
