import type { Agent, FleetSummary } from "./types";

const now = new Date().toISOString();
const ago = (min: number) => new Date(Date.now() - min * 60000).toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86400000).toISOString();

export const agents: Agent[] = [
  // ═══════════════════════════════════════════════════════════════
  // FLICKER EFFECT AGENTS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "nathan-01",
    name: "Nathan Reid",
    owner: "Chris Steele",
    environment: "prod",
    tags: ["executive-assistant", "strategic-advisor", "primary"],
    slaTier: "critical",
    status: "online",
    lastHeartbeat: ago(2),
    lastSeen: ago(1),
    currentTask: "Agent ops dashboard build",
    queueDepth: 0,
    uptime: "13d 8h",
    agentVersion: "2026.4.9",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw 2026.4.9",
    toolingVersion: "Node v22.22.2",
    versionDrift: true,
    host: {
      name: "flicker-swarm-01",
      ip: "178.104.157.99",
      location: "Helsinki, FI (Hetzner)",
      cpu: 35,
      ram: 37,
      disk: 16,
      network: "healthy",
    },
    errors1h: 0,
    errors24h: 1,
    taskStartDelay: 280,
    completionTime: 9500,
    apiLatency: 160,
    cost: {
      today: 18.50,
      week: 112.00,
      month: 480.00,
      tokensToday: 1_500_000,
      model: "anthropic/claude-opus-4-6",
    },
    permissions: ["exec", "read", "write", "web_fetch", "web_search", "git", "gmail", "calendar", "drive", "sharepoint", "ssh-remote"],
    lastBackup: daysAgo(1),
    lastRestoreTest: null,
    backupHealthy: true,
    secrets: { total: 12, expiringSoon: 2, expired: 0, lastRotation: daysAgo(3) },
    autoRestart: true,
    lastRestartReason: "Gateway restart for MCP fix",
    lastRestartTime: ago(180),
    security: {
      patchLevel: "2026-04-09",
      lastOsUpdate: "2026-04-09",
      firewallStatus: "active",
      portsExposed: [18789, 22],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: false,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: true,
      auditRetentionDays: 30,
      lastVulnScan: null,
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Daily 03:00-05:00 UTC",
    approvedModels: ["anthropic/claude-opus-4-6", "zai/glm-5.1", "anthropic/claude-sonnet-4-6"],
    fallbackChain: ["zai/glm-5.1", "anthropic/claude-sonnet-4-6"],
    timeline: [
      { time: ago(180), type: "restart", message: "Gateway restart — Google Workspace MCP re-auth" },
      { time: daysAgo(1), type: "deploy", message: "Trailer besiktning checker deployed to tangiamo-ser" },
      { time: daysAgo(1), type: "deploy", message: "59 repos mirrored TrustPlayTech → Manserio" },
      { time: daysAgo(1), type: "security", message: "Redis firewall applied on Chloe 36G (204.168.131.248)" },
      { time: daysAgo(2), type: "config", message: "Google OAuth re-auth for chris00steele + chrissteeletangiamo" },
      { time: daysAgo(7), type: "deploy", message: "FoU-avdrag package uploaded to SharePoint" },
    ],
  },
  {
    id: "katelyn-02",
    name: "Katelyn Summers",
    owner: "Chris Steele",
    environment: "prod",
    tags: ["growth", "marketing", "flicker-effect"],
    slaTier: "high",
    status: "online",
    lastHeartbeat: ago(15),
    lastSeen: ago(10),
    currentTask: null,
    queueDepth: 0,
    uptime: "13d 8h",
    agentVersion: "2026.4.9",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw 2026.4.9",
    toolingVersion: "Node v22.22.2",
    versionDrift: true,
    host: {
      name: "flicker-swarm-01",
      ip: "178.104.157.99",
      location: "Helsinki, FI (Hetzner)",
      cpu: 35,
      ram: 37,
      disk: 16,
      network: "healthy",
    },
    errors1h: 0,
    errors24h: 0,
    taskStartDelay: 350,
    completionTime: 7200,
    apiLatency: 140,
    cost: {
      today: 4.20,
      week: 28.00,
      month: 95.00,
      tokensToday: 380_000,
      model: "zai/glm-5.1",
    },
    permissions: ["exec", "read", "write", "web_fetch", "web_search", "git"],
    lastBackup: daysAgo(1),
    lastRestoreTest: null,
    backupHealthy: true,
    secrets: { total: 4, expiringSoon: 0, expired: 0, lastRotation: daysAgo(14) },
    autoRestart: true,
    lastRestartReason: "Heartbeat cycle",
    lastRestartTime: ago(30),
    security: {
      patchLevel: "2026-04-09",
      lastOsUpdate: "2026-04-09",
      firewallStatus: "active",
      portsExposed: [18789, 22],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: false,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: true,
      auditRetentionDays: 30,
      lastVulnScan: null,
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Daily 03:00-05:00 UTC",
    approvedModels: ["zai/glm-5.1"],
    fallbackChain: ["anthropic/claude-sonnet-4-6"],
    timeline: [
      { time: daysAgo(2), type: "config", message: "Rebranded from Chloe Sykes to Katelyn Summers" },
      { time: daysAgo(5), type: "deploy", message: "Flicker Effect website content updates" },
    ],
  },
  {
    id: "sloane-03",
    name: "Sloane Navarro",
    owner: "Chris Steele",
    environment: "prod",
    tags: ["cto", "opnet", "smart-contracts", "infrastructure"],
    slaTier: "critical",
    status: "online",
    lastHeartbeat: ago(8),
    lastSeen: ago(5),
    currentTask: null,
    queueDepth: 0,
    uptime: "1d 22h",
    agentVersion: "2026.4.15",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw 2026.4.15",
    toolingVersion: "Node v22.22.2",
    versionDrift: false,
    host: {
      name: "Gideon-flicker-1",
      ip: "77.42.81.193",
      location: "Helsinki, FI (Hetzner)",
      cpu: 12,
      ram: 19,
      disk: 17,
      network: "healthy",
    },
    errors1h: 0,
    errors24h: 0,
    taskStartDelay: 300,
    completionTime: 11000,
    apiLatency: 170,
    cost: {
      today: 12.00,
      week: 78.00,
      month: 310.00,
      tokensToday: 980_000,
      model: "anthropic/claude-opus-4-6",
    },
    permissions: ["exec", "read", "write", "web_fetch", "web_search", "git", "deploy"],
    lastBackup: null,
    lastRestoreTest: null,
    backupHealthy: false,
    secrets: { total: 6, expiringSoon: 0, expired: 0, lastRotation: daysAgo(10) },
    autoRestart: true,
    lastRestartReason: "claude-mem plugin disabled + gateway restart",
    lastRestartTime: daysAgo(0),
    security: {
      patchLevel: "2026-04-15",
      lastOsUpdate: "2026-04-15",
      firewallStatus: "active",
      portsExposed: [18789, 22],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: false,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: true,
      auditRetentionDays: 30,
      lastVulnScan: null,
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Tue/Thu 03:00-05:00 UTC",
    approvedModels: ["anthropic/claude-opus-4-6", "openai/gpt-5.4-pro"],
    fallbackChain: ["anthropic/claude-sonnet-4-6"],
    timeline: [
      { time: daysAgo(0), type: "config", message: "claude-mem plugin disabled and service killed" },
      { time: daysAgo(5), type: "alert", message: "SSH unreachable — resolved after Hetzner maintenance" },
    ],
  },
  {
    id: "henry-04",
    name: "Henry Oliver",
    owner: "Chris Steele",
    environment: "prod",
    tags: ["cto", "frontend", "backend"],
    slaTier: "medium",
    status: "online",
    lastHeartbeat: ago(20),
    lastSeen: ago(15),
    currentTask: null,
    queueDepth: 0,
    uptime: "12d 11h",
    agentVersion: "2026.3.24",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw 2026.3.24",
    toolingVersion: "Node v22.22.0",
    versionDrift: true,
    host: {
      name: "316-44-1",
      ip: "204.168.193.91",
      location: "Helsinki, FI (Hetzner)",
      cpu: 8,
      ram: 14,
      disk: 8,
      network: "healthy",
    },
    errors1h: 0,
    errors24h: 0,
    taskStartDelay: 400,
    completionTime: 8500,
    apiLatency: 155,
    cost: {
      today: 2.10,
      week: 14.00,
      month: 52.00,
      tokensToday: 180_000,
      model: "anthropic/claude-sonnet-4-6",
    },
    permissions: ["exec", "read", "write", "web_fetch", "git"],
    lastBackup: null,
    lastRestoreTest: null,
    backupHealthy: false,
    secrets: { total: 3, expiringSoon: 0, expired: 0, lastRotation: null },
    autoRestart: true,
    lastRestartReason: null,
    lastRestartTime: null,
    security: {
      patchLevel: "2026-03-24",
      lastOsUpdate: "2026-03-24",
      firewallStatus: "unknown",
      portsExposed: [18789, 22, 80],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: false,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: false,
      auditRetentionDays: 0,
      lastVulnScan: null,
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Not configured",
    approvedModels: ["anthropic/claude-sonnet-4-6"],
    fallbackChain: [],
    timeline: [
      { time: daysAgo(3), type: "config", message: "Paperclip ops dashboard hosted on port 80" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // 36 GROUP AGENTS
  // ═══════════════════════════════════════════════════════════════
  {
    id: "gideon-05",
    name: "Gideon Frost",
    owner: "Chris Steele",
    environment: "prod",
    tags: ["cto", "36-group", "tangiamo"],
    slaTier: "high",
    status: "degraded",
    lastHeartbeat: ago(10),
    lastSeen: ago(8),
    currentTask: null,
    queueDepth: 0,
    uptime: "9d 7h",
    agentVersion: "2026.4.9",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw 2026.4.9",
    toolingVersion: "Node v22.22.1",
    versionDrift: true,
    host: {
      name: "36g-cto-gideon-nbg1-01",
      ip: "46.224.57.251",
      location: "Nuremberg, DE (Hetzner)",
      cpu: 15,
      ram: 34,
      disk: 84,
      network: "healthy",
    },
    errors1h: 0,
    errors24h: 3,
    taskStartDelay: 450,
    completionTime: 12000,
    apiLatency: 190,
    cost: {
      today: 6.50,
      week: 42.00,
      month: 165.00,
      tokensToday: 520_000,
      model: "anthropic/claude-opus-4-6",
    },
    permissions: ["exec", "read", "write", "web_fetch", "web_search", "git"],
    lastBackup: null,
    lastRestoreTest: null,
    backupHealthy: false,
    secrets: { total: 5, expiringSoon: 1, expired: 0, lastRotation: daysAgo(12) },
    autoRestart: true,
    lastRestartReason: "OpenClaw update to 2026.4.9",
    lastRestartTime: daysAgo(9),
    security: {
      patchLevel: "2026-04-10",
      lastOsUpdate: "2026-04-10",
      firewallStatus: "active",
      portsExposed: [18789, 22],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: false,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: true,
      auditRetentionDays: 30,
      lastVulnScan: null,
      criticalFindings: 1,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Wed 03:00-05:00 UTC",
    approvedModels: ["anthropic/claude-opus-4-6"],
    fallbackChain: ["anthropic/claude-sonnet-4-6"],
    timeline: [
      { time: daysAgo(0), type: "alert", message: "⚠️ Disk usage at 84% — needs cleanup" },
      { time: daysAgo(9), type: "deploy", message: "Updated to OpenClaw 2026.4.9" },
      { time: daysAgo(12), type: "security", message: "SSH key injected via Hetzner rescue mode" },
    ],
  },
  {
    id: "chloe36g-06",
    name: "Chloe Sykes (36G)",
    owner: "Chris Steele",
    environment: "prod",
    tags: ["growth", "36-group", "blizz"],
    slaTier: "high",
    status: "online",
    lastHeartbeat: ago(5),
    lastSeen: ago(3),
    currentTask: null,
    queueDepth: 0,
    uptime: "3d 3h",
    agentVersion: "2026.4.14",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw 2026.4.14",
    toolingVersion: "Node v22.22.1",
    versionDrift: true,
    host: {
      name: "36g-growth-chloe-hel1-01",
      ip: "204.168.131.248",
      location: "Helsinki, FI (Hetzner)",
      cpu: 10,
      ram: 25,
      disk: 30,
      network: "healthy",
    },
    errors1h: 0,
    errors24h: 0,
    taskStartDelay: 300,
    completionTime: 7800,
    apiLatency: 145,
    cost: {
      today: 5.80,
      week: 38.00,
      month: 142.00,
      tokensToday: 480_000,
      model: "anthropic/claude-opus-4-6",
    },
    permissions: ["exec", "read", "write", "web_fetch", "web_search", "git"],
    lastBackup: null,
    lastRestoreTest: null,
    backupHealthy: false,
    secrets: { total: 5, expiringSoon: 0, expired: 0, lastRotation: daysAgo(7) },
    autoRestart: true,
    lastRestartReason: "Routine restart",
    lastRestartTime: daysAgo(3),
    security: {
      patchLevel: "2026-04-14",
      lastOsUpdate: "2026-04-14",
      firewallStatus: "active",
      portsExposed: [18789, 22, 6379],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: false,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: true,
      auditRetentionDays: 30,
      lastVulnScan: daysAgo(1),
      criticalFindings: 1,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Not configured",
    approvedModels: ["anthropic/claude-opus-4-6"],
    fallbackChain: ["anthropic/claude-sonnet-4-6"],
    timeline: [
      { time: daysAgo(1), type: "security", message: "BSI alert: Redis port 6379 exposed — iptables fix applied by Nathan" },
      { time: daysAgo(1), type: "security", message: "Redis firewall rules added: blocked from internet, localhost + Docker only" },
      { time: daysAgo(3), type: "restart", message: "Routine gateway restart" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // GREG CARSON / KINGBEE SWARM
  // ═══════════════════════════════════════════════════════════════
  {
    id: "aristotle-07",
    name: "Aristotle (KingBee Lead)",
    owner: "Greg Carson",
    environment: "prod",
    tags: ["kingbee", "lead-agent", "swarm"],
    slaTier: "high",
    status: "online",
    lastHeartbeat: ago(5),
    lastSeen: ago(3),
    currentTask: "Swarm coordination",
    queueDepth: 0,
    uptime: "7d+",
    agentVersion: "2026.4.x",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw",
    toolingVersion: "Node v22.x",
    versionDrift: false,
    host: {
      name: "openclaw-swarm-01",
      ip: "116.203.135.248",
      location: "Nuremberg, DE (Hetzner)",
      cpu: 20,
      ram: 40,
      disk: 45,
      network: "healthy",
    },
    errors1h: 0,
    errors24h: 0,
    taskStartDelay: 300,
    completionTime: 10000,
    apiLatency: 175,
    cost: {
      today: 22.00,
      week: 145.00,
      month: 580.00,
      tokensToday: 1_800_000,
      model: "anthropic/claude-opus-4-6",
    },
    permissions: ["exec", "read", "write", "web_fetch", "web_search", "git", "deploy", "ssh-remote"],
    lastBackup: daysAgo(12),
    lastRestoreTest: null,
    backupHealthy: true,
    secrets: { total: 15, expiringSoon: 0, expired: 0, lastRotation: daysAgo(14) },
    autoRestart: true,
    lastRestartReason: null,
    lastRestartTime: null,
    security: {
      patchLevel: "2026-04-10",
      lastOsUpdate: "2026-04-10",
      firewallStatus: "active",
      portsExposed: [22, 18789],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: true,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: true,
      auditRetentionDays: 30,
      lastVulnScan: null,
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Not configured",
    approvedModels: ["anthropic/claude-opus-4-6"],
    fallbackChain: ["anthropic/claude-sonnet-4-6"],
    timeline: [
      { time: daysAgo(2), type: "deploy", message: "KingBee swarm operations ongoing" },
      { time: daysAgo(12), type: "config", message: "Backup + vault + recovery docs updated" },
    ],
  },
  {
    id: "bob-08",
    name: "Bob Caribe",
    owner: "Greg Carson",
    environment: "prod",
    tags: ["kingbee", "sub-agent"],
    slaTier: "medium",
    status: "online",
    lastHeartbeat: ago(10),
    lastSeen: ago(8),
    currentTask: null,
    queueDepth: 0,
    uptime: "7d+",
    agentVersion: "2026.4.x",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw",
    toolingVersion: "Node v22.x",
    versionDrift: false,
    host: {
      name: "bob-caribe-01",
      ip: "178.104.129.171",
      location: "Helsinki, FI (Hetzner)",
      cpu: 10,
      ram: 25,
      disk: 20,
      network: "healthy",
    },
    errors1h: 0,
    errors24h: 0,
    taskStartDelay: 350,
    completionTime: 8000,
    apiLatency: 160,
    cost: {
      today: 3.50,
      week: 22.00,
      month: 88.00,
      tokensToday: 290_000,
      model: "anthropic/claude-opus-4-6",
    },
    permissions: ["exec", "read", "write", "web_fetch", "git"],
    lastBackup: null,
    lastRestoreTest: null,
    backupHealthy: false,
    secrets: { total: 3, expiringSoon: 0, expired: 0, lastRotation: null },
    autoRestart: true,
    lastRestartReason: null,
    lastRestartTime: null,
    security: {
      patchLevel: "2026-04-01",
      lastOsUpdate: "2026-04-01",
      firewallStatus: "unknown",
      portsExposed: [22, 18789],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: false,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: false,
      auditRetentionDays: 0,
      lastVulnScan: null,
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Not configured",
    approvedModels: ["anthropic/claude-opus-4-6"],
    fallbackChain: [],
    timeline: [],
  },
  {
    id: "ada-09",
    name: "Ada Lovelace",
    owner: "Greg Carson",
    environment: "prod",
    tags: ["kingbee", "sub-agent"],
    slaTier: "medium",
    status: "online",
    lastHeartbeat: ago(12),
    lastSeen: ago(10),
    currentTask: null,
    queueDepth: 0,
    uptime: "7d+",
    agentVersion: "2026.4.x",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw",
    toolingVersion: "Node v22.x",
    versionDrift: false,
    host: {
      name: "ada-lovelace-02",
      ip: "116.203.68.90",
      location: "Nuremberg, DE (Hetzner)",
      cpu: 8,
      ram: 20,
      disk: 15,
      network: "healthy",
    },
    errors1h: 0,
    errors24h: 0,
    taskStartDelay: 380,
    completionTime: 9000,
    apiLatency: 165,
    cost: {
      today: 2.80,
      week: 18.00,
      month: 72.00,
      tokensToday: 230_000,
      model: "anthropic/claude-opus-4-6",
    },
    permissions: ["exec", "read", "write", "web_fetch", "git"],
    lastBackup: null,
    lastRestoreTest: null,
    backupHealthy: false,
    secrets: { total: 2, expiringSoon: 0, expired: 0, lastRotation: null },
    autoRestart: true,
    lastRestartReason: null,
    lastRestartTime: null,
    security: {
      patchLevel: "2026-04-01",
      lastOsUpdate: "2026-04-01",
      firewallStatus: "unknown",
      portsExposed: [22, 18789],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: false,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: false,
      auditRetentionDays: 0,
      lastVulnScan: null,
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Not configured",
    approvedModels: ["anthropic/claude-opus-4-6"],
    fallbackChain: [],
    timeline: [],
  },
  {
    id: "woz-10",
    name: "Woz Agent",
    owner: "Greg Carson",
    environment: "prod",
    tags: ["kingbee", "sub-agent"],
    slaTier: "medium",
    status: "online",
    lastHeartbeat: ago(15),
    lastSeen: ago(12),
    currentTask: null,
    queueDepth: 0,
    uptime: "7d+",
    agentVersion: "2026.4.x",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw",
    toolingVersion: "Node v22.x",
    versionDrift: false,
    host: {
      name: "woz-agent-01",
      ip: "46.225.96.146",
      location: "Nuremberg, DE (Hetzner)",
      cpu: 5,
      ram: 18,
      disk: 12,
      network: "healthy",
    },
    errors1h: 0,
    errors24h: 0,
    taskStartDelay: 400,
    completionTime: 8500,
    apiLatency: 170,
    cost: {
      today: 2.20,
      week: 15.00,
      month: 58.00,
      tokensToday: 180_000,
      model: "anthropic/claude-opus-4-6",
    },
    permissions: ["exec", "read", "write", "web_fetch", "git"],
    lastBackup: null,
    lastRestoreTest: null,
    backupHealthy: false,
    secrets: { total: 2, expiringSoon: 0, expired: 0, lastRotation: null },
    autoRestart: true,
    lastRestartReason: null,
    lastRestartTime: null,
    security: {
      patchLevel: "2026-04-01",
      lastOsUpdate: "2026-04-01",
      firewallStatus: "unknown",
      portsExposed: [22, 18789],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: false,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: false,
      auditRetentionDays: 0,
      lastVulnScan: null,
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Not configured",
    approvedModels: ["anthropic/claude-opus-4-6"],
    fallbackChain: [],
    timeline: [],
  },
  {
    id: "opnet-screener-11",
    name: "OpNet Screener",
    owner: "Greg Carson",
    environment: "prod",
    tags: ["kingbee", "opnet", "screening"],
    slaTier: "low",
    status: "online",
    lastHeartbeat: ago(20),
    lastSeen: ago(15),
    currentTask: null,
    queueDepth: 0,
    uptime: "7d+",
    agentVersion: "2026.4.x",
    latestVersion: "2026.4.15",
    systemVersion: "OpenClaw",
    toolingVersion: "Node v22.x",
    versionDrift: false,
    host: {
      name: "opnetscreener",
      ip: "178.104.142.196",
      location: "Helsinki, FI (Hetzner)",
      cpu: 5,
      ram: 15,
      disk: 10,
      network: "healthy",
    },
    errors1h: 0,
    errors24h: 0,
    taskStartDelay: 500,
    completionTime: 6000,
    apiLatency: 180,
    cost: {
      today: 1.50,
      week: 10.00,
      month: 40.00,
      tokensToday: 120_000,
      model: "anthropic/claude-sonnet-4-6",
    },
    permissions: ["exec", "read", "write", "web_fetch"],
    lastBackup: null,
    lastRestoreTest: null,
    backupHealthy: false,
    secrets: { total: 1, expiringSoon: 0, expired: 0, lastRotation: null },
    autoRestart: true,
    lastRestartReason: null,
    lastRestartTime: null,
    security: {
      patchLevel: "2026-04-01",
      lastOsUpdate: "2026-04-01",
      firewallStatus: "unknown",
      portsExposed: [22],
      sshPasswordDisabled: true,
      sshKeyOnly: true,
      fail2ban: false,
      diskEncryption: false,
      mfaEnabled: false,
      auditLogEnabled: false,
      auditRetentionDays: 0,
      lastVulnScan: null,
      criticalFindings: 0,
      networkLocation: "cloud",
    },
    maintenanceWindow: "Not configured",
    approvedModels: ["anthropic/claude-sonnet-4-6"],
    fallbackChain: [],
    timeline: [],
  },
];

export function getFleetSummary(): FleetSummary {
  const total = agents.length;
  const online = agents.filter((a) => a.status === "online").length;
  const degraded = agents.filter((a) => a.status === "degraded").length;
  const offline = agents.filter((a) => a.status === "offline").length;
  const stuck = agents.filter((a) => a.status === "stuck").length;
  return {
    total,
    online,
    degraded,
    offline,
    stuck,
    healthyPct: Math.round((online / total) * 100),
  };
}

export function getNeedsAttention(): Agent[] {
  return agents.filter((a) => {
    if (a.status === "offline" || a.status === "stuck" || a.status === "degraded") return true;
    if (a.versionDrift) return true;
    if (a.errors24h > 5) return true;
    if (a.secrets.expiringSoon > 0 || a.secrets.expired > 0) return true;
    if (a.security.criticalFindings > 0) return true;
    if (!a.backupHealthy) return true;
    if (a.host.disk > 80) return true;
    return false;
  });
}

